---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: aks-test
spec:
  encryptedData:
    mongo-password: AgBRWHsnrZWYW0vvX9dvUdy4+8gCGutGoT+1UNHIgf8wKgOBGG6TNuua+v1z0l8VBZjfeW4EfXxnY+7WORpcbrG/LrL497stggBvo3vIzIWdBjcrRl+Z3+NuHoBZi+pS4q/zMT+BEenPOKQsQVGSBSixn85ypo1QlUOZB7nt0WAK52mjiG3XX9Nur1BqT4X0/vk2tbjD7BOaeTT3JMhnM2TJO1Aqx7lTCjbmp6E9p2Xl+ZomJ/4JMPsi74DjhM+R1LMDgx/inGGZRkqndEZav5PWF2+y2mIJbJyNdpmxhgRyTJFm3otoKe3HDCtlT3Y03N4xciAueX2rdqwTF3nhVhMzry8vUS8EQlbsLSyhZsUieJDZFLvQZOAMzf91o5rlHp82ek1dMlKMbc/jQu+QJ3mLNdzX0Rggfm7SwVsvCuEAgZw95UTx8Bt5RLOTihBQbAe4m30QIc4hlOplo4PszZYQV343TVGfhLkQxNYedZ4pZ1eT0PSSw2nKkSgYlN7IR5nY3vnW+dUAB/fitk8YDdXJp7tlqZcXLnaB4EOMLv0UfJAOim6qBQ8izdBSXqOSEpiOQ8uSt1z4h8Gr6ezTSYeYQXYYHiQHr8+dSqdPkV9wQR5DE0y9l4RuTmpeIOBhS/qylGsiBvYl6xdPzs1tWiZAiQCRQgPQeaWOQ0BZuywcYfc8TN17un6VyjH3RV5EgYq94gu5FUxJJFoUSNOwEanb/w==
    mongo-user: AgAgtwcxa6u179zhcmeVoDZL61cTM8bQ/H+cwh0Pq3uN8Vvz2llpOQ7NdrKTrcb0v4yWrX4WfVexX87TuJMtAL66rEbH097xD8ev5e9KlxJh9qPIQcCuBDhFjGmrWxoy23KqQ8TuepAqm3bU94WMk1pfeeWDc1i9RY69Sa1VPJ/MEV8ic0l7q2ItFzkG2PIMi/X2Jg5xQ0PjishEpLgEjhfT6FOjOgt9wDVjL8wKLRRikSbo3XC052LD8Voy9x+afO6pmsdII0o/hw3hoysZBtFaOSPIcRlOrXLKgWBcSLwEHbLT0nDUsuNa19eP/jdijE8KT3m0dzcfWFBgL2eYM0336VQAcZToI6pCiAkYALXSPvLWQFLcJJmhX0ldiGVYOfF1UyfLEF6zFqfX2DJCTe2MtAh0UYjtkwQw4Y9rPuFVz58oYsoEkB0ReqpSYTluEFIcB4U/ccZZuHcTENby0rZDfbTxXFp7wJjJthxLzO1HCU/RUguFq8MEWfscLiTSQKz5QE/ztQHNfRr87G8+XRgzbACzt7mxbQtt6D0AalRpWa/vCGdStK8gVsNEX7NtqbdJo/CnsO8g6jPHqpaWDx97oBoOHwvczQ9WtuhF8Ezmn9EJDlGeEWzkD3bJvO2Hb7hu7Yh6+fHjyx8m3k57l2QCr8egl6VsPaGOJsToj6vcNVhn1cOdtJZvtZU1avH9Ij2jbiZYh8Wy5E0=
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aks-test
    type: Opaque
