---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: aks-test
  annotations:
    # Sync wave -1 ensures secrets are created first
    argocd.argoproj.io/sync-wave: "-1"
spec:
  encryptedData:
    mongo-password: AgABKHCk4JVJej6J4gxJo+cRuB1ytmcNwlzIQ00FGmj1UlNOYegLmjlxYcs8IAbIxBP0kgBjq83tvnaPADU/djsPbBNBeWCrbngEals2XogLgn6AJs9BMTk5QHAzLK6ki5zqtYyBiMxfm70YcKTPhA8m65j4JaCFN/MP+gkONzydrKp5ANNAVIOt34teVXN1DaOPNzvWGObCzVKD0HKfd7DkwF7V1H7EGbiyP8j3QxIPnt9pV0L+EXC4BnzeTvgv37iDDXPRdWlfA+jMJSNbWRzoVipbHiZrBCYROaizwfuU8Oapy2gAaOQBiiDXktL78TfB6eBa9kgqjdeZqVKxaAXPtRq1miJoRGw5dLGRYca7GcYxdHx98Y7L+MrChfcp9w9pwf5W6/kDnVKoWGT6OjK9QKFvAjFRohWaTKlFMdqxkRFqLKrT52KRUP5G3o0PAYd3hN08AanDYhBM4wIPhIOLZmuWdrjeRpKh00AWtgEUwBLywiUo4MMTERoq7s+AanVWazMmpaQQPtgNVclErOGfih2k0re1/JAiD+4BX6U4I26S7I3k68/Uo3XW0m8p5yaCEUKxXMvFBRkPvQtaOY6gTDvW9IItO2h7cJLq7TyKhh9q/2y9HQAc6HF+VzRs66tZxz4Y7LH5Jed7zMCX0UP584N+HRCQXRNZccDjpmknTHVnuwY9o+Q0lmBcaog2D3sNGCxiwyfkIBMDGOKErxkz4A==
    mongo-user: AgAYpPgfbkEsCD3cyVpOkXtBAPJyf92VGthbBBdxdWo1t4S8EoPQ9vgZxyDTAkGeT0+/VT1ZGEjcGgbJubxTCqikfnd9dOe4fRB6Z+88U8/jJlqV/CVmJzcvrnhvzoXhElSJJ3LGZAp1rYu9JLzBhW0caK0x1d178/HxmeZkMzbYUUZAyURueMPO+3KJiNiUxlicLJVL1atWqnYQih2B5m0d+tydczyv4x8SXYIFO3svMPfCDDSX1Xf2lbdBiNyP/+fX3p9w/u++xSq/t2qJSU1MD26tO+5xE7FqOGJGPXK0vIhkdro4ctvEgPFZ/g2p2QIzxvz5zxdD/Qu2nzPawQHJ9wA9OcKUJAr+YaqGWexi/wjrvSEjdwKr5ZK+SB7bDKCc7yyFDTo8TjjR7sU4uuXC6XEv+sX/hGepA7nMXi7AmymAaLvikXWGihGpcY7Hjw18SBBktY3L5e1pIhmO+btN9hou2devU/+CRh2+g45IjblKBeC0tvK9HEGKkZWCBpQKe3CZ/fC3vHMQoC09NgvZweX0QH73daCzvrfITJjHqXQN6mY9CIFMZ2yu96eVx2/YFqS+997UDD9al6OYRhsbqai+AlXKG9MIRBj079qeiOjxEonAMEawli7iXq8jdSQBmVhS7bE1lFKVJMw9EVdezT4oIqUPkEQRAE7KGcY2rbj7XozvNNyjJPkg4UTsmIRo35uDsxT4zzQ=
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: aks-test
    type: Opaque
